### ISSUE TITLE
threaded example

### ISSUE THREAD

**Issue by paulvollmer** [whg/ofxTerminal#1]
hello,
i've using your addon and it is really nice.
at the moment i'm using a threaded terminal to run a bit faster.
i can create a new example and add the threaded terminal.

what do you think?

**Comment by whg** [comment]
Hi,

Sounds good, I would be interested in seeing it. Feel fee to submit a pull request and I'll integrate it into the main repo.

**Comment by paulvollmer** [comment]
here is the pull request...
https://github.com/whg/ofxTerminal/pull/2

this issue is closed right now
